import { TasksContextProvider } from '@/contexts/tasks-context';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TasksContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex items-center justify-center m-5 md:h-[100vh] md:m-auto max-w-[80rem]">
            {children}
          </div>
        </body>
      </html>
    </TasksContextProvider>
  );
}
